### ISSUE TITLE
Document purpose and necessity of grid boundary rectangle

### ISSUE THREAD

**Issue by philipbelesky** [Sunknight1986/Eagle-Eye#1]
This rectangle is a key parameter to set so that the field-grip parts of the definition work. However, it is in the middle of the definition and hard to notice. It would be helpful to draw attention to it, or locate it next to the other key inputs (e.g. OSM file).

<img width="522" alt="Screen Shot 2021-08-30 at 3 48 16 pm" src="https://user-images.githubusercontent.com/495961/131291390-e4df4a1c-be09-4be5-8028-562ffddd79a9.png">

**Comment by philipbelesky** [comment]
(I realise this is documented in the README, but it can be helpful to make it obvious in the definition as well!)

**Comment by MichelleTamm** [comment]
Hi Clark!thank you for sending me a learning video,but I don't know why I can not get the outlook like you show on the readme and the video,I have check my battery connection and found that nothing wrong with it,but it present a result like this:

(for copenhagen map 1:500)
![572c7da0ebb62287349ec6742b832da](https://user-images.githubusercontent.com/88995973/132295402-07b8e3ef-3d60-4751-b1f2-57571f683e25.png)

![51a27b7e56b9c423e8b91ad9ecf3be1](https://user-images.githubusercontent.com/88995973/132295419-269c4f25-f5e7-4c2d-87e2-8a276eec6b7d.png)

![72424faca6a38827d2801c2f3083598](https://user-images.githubusercontent.com/88995973/132295509-b38eccb0-76d6-43f1-8711-b2aac0b476b5.png)

1.there have no result like you draw a rectangle then the color map for the pharmacy and hospital show up.
2.when I change all of the number slider in your connection,there have nothing to change with
3.all I can see from the grasshopper is that I can find out the data of highway,I think it is very strange,
4.still,not only for the city of Copenhagen shows this matters,but also for city of Gaza.

If you can,I want you can give me a more detailed instructions for your plugin,thank you so much!

**Comment by sterna-paradisaea-777** [comment]
**Text feedback**
It's a really attractive idea and a great structure. And thanks for your video instruction which is clear and helpful.

The file runs very well on my site except for one part. [imagine below]
Does this error have an effect on the results? 
![1631005957(1)](https://user-images.githubusercontent.com/88767205/132322823-c6dc1f43-97e8-4a51-825d-7b8a01df9e8a.jpg)

**Comment by Sunknight1986** [comment]
@sterna-paradisaea-777, Thanks for the feedback and sorry for so late reply, I thought there will be a new issue made by peers so I haven't checked the issue left by Philip for the whole week. I apologize for that!
Yes, it is normal and I put a notice upon it but it should be more obvious. I will make the explanation about the red component (maybe draw an arrow to point it) more precise. Thank you again!
BTW, next time pls make a new issue if it is possible in case this kind of delayed reply happen again :)

**Comment by Sunknight1986** [comment]
@MichelleTamm, Thanks for the feedback and sorry for so late reply, I thought there will be a new issue made by peers so I haven't checked the issue left by Philip for the whole week. I apologize for that!!
I tried to recreate your problem in my tool, but it seems like working fine...

**The distribution of hospitals/pharmacies in Gaza city:**
![微信图片_20210913084842](https://user-images.githubusercontent.com/88772212/133010383-d1e225fe-7cfd-4150-b432-f3c6cce9f93a.png)

**in Copenhagen, 1:500:**
![微信截图_20210913091657](https://user-images.githubusercontent.com/88772212/133010510-658fd40c-2f99-4e2a-8a54-7e292a141c8f.png)
![微信截图_20210913085632](https://user-images.githubusercontent.com/88772212/133010430-01e21b99-86f6-497d-9181-796433fb25a8.png)


**in Copenhagen, 1:3000:**
![微信截图_20210913090424](https://user-images.githubusercontent.com/88772212/133010325-4e183eba-feac-45b6-995a-80b7f8592408.png)
![微信截图_20210913090436](https://user-images.githubusercontent.com/88772212/133010363-dda0618e-91e0-4fda-8f03-f6edb04df4c8.png)

In addition, **I didn't adjust any parameter but just the default number.** So, I reckon it may be because your site is too small to contain a pharmacy/hospital?  You could disable preview of the final components but open these two components:

![微信截图_20210913092221](https://user-images.githubusercontent.com/88772212/133011300-bf7b6845-9a93-4ed9-8b5f-0631969e014c.png)


to make sure this issue. For example, in this screenshot of Copenhagen 1:500, there are some pharmacies but just no hospitals (in points - there should be some with lines - I will improve it in the next version)in this area.

BTW, next time pls make a new issue if it is possible in case this kind of delayed reply happen again :)

**Comment by MichelleTamm** [comment]
Thank you clark，I will do it again！
________________________________
发件人: Sunknight1986 ***@***.***>
发送时间: 2021年9月13日 11:37
收件人: Sunknight1986/Eagle-Eye ***@***.***>
抄送: Kaiwen Tan ***@***.***>; Mention ***@***.***>
主题: Re: [Sunknight1986/Eagle-Eye] Document purpose and necessity of grid boundary rectangle (#1)


@MichelleTamm<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMichelleTamm&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629835095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qyulmLbi7OZAaXgXU9OcKosqPSGYjZVwqISCHF%2BY%2Ffg%3D&reserved=0>, Thanks for the feedback and sorry for so late reply, I thought there will be a new issue made by peers so I haven't checked the issue left by Philip for the whole week. I apologize for that!!
I tried to recreate your problem in my tool, but it seems like working fine...

The distribution of hospitals/pharmacies in Gaza city:
[微信图片_20210913084842]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133010383-d1e225fe-7cfd-4150-b432-f3c6cce9f93a.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629835095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i0TjLIx5e1HpyfiijjtgqUqKy1P%2FemC%2FXt9thWpVHto%3D&reserved=0>

in Copenhagen, 1:500:
[微信截图_20210913091657]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133010510-658fd40c-2f99-4e2a-8a54-7e292a141c8f.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629845024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uVdIJoZxeEXq5FcWfwfKLBqo8DT4V16euO6sF6MTdYo%3D&reserved=0>
[微信截图_20210913085632]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133010430-01e21b99-86f6-497d-9181-796433fb25a8.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629845024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1NwQ9R1wGaSfwQTVq8M3Py7o8TXZnIAuHOJv%2B8Xbvog%3D&reserved=0>

in Copenhagen, 1:3000:
[微信截图_20210913090424]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133010325-4e183eba-feac-45b6-995a-80b7f8592408.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629854989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j4xsNGZxAwxHTVkm0Yt623dd%2FWBg2wKGzNI7uat%2BGhw%3D&reserved=0>
[微信截图_20210913090436]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133010363-dda0618e-91e0-4fda-8f03-f6edb04df4c8.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629854989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Swo3XHStpAqHZ4vKGi3cHUQda8KyPOKVNmYzc%2FHlbtI%3D&reserved=0>

In addition, I didn't adjust any parameter but just the default number. So, I reckon it may be because your site is too small to contain a pharmacy/hospital? You could disable preview of the final components but open these two components:

[微信截图_20210913092221]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F88772212%2F133011300-bf7b6845-9a93-4ed9-8b5f-0631969e014c.png&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629864960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3SESD%2F4znZIVxQ7oa6yeK7OYB9iS7CRF1I0cWunrjLE%3D&reserved=0>

to make sure this issue. For example, in this screenshot of Copenhagen 1:500, there are some pharmacies but just no hospitals (in points - there should be some with lines - I will improve it in the next version)in this area.

BTW, next time pls make a new issue if it is possible in case this kind of delayed reply happen again :)

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunknight1986%2FEagle-Eye%2Fissues%2F1%23issuecomment-917767891&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629864960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EGCZumupuPqgfGfjguDWMQuuhd2Ay0OMt20HPR0A4Cg%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVG7RBMXFT7ZOSJPQL72AL3UBVIWDANCNFSM5DBEGTXA&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629874920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vdY4iAEN7RFqT%2FDECjim11VYEIA2nMYhAhp0LvIHFJo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629874920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i3Fer0ka0gj2CbGOHKR%2BvH6dBZfqYjXs%2Bgrt%2BA2t1FA%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cs3777526%40student.rmit.edu.au%7C5a7e97f3e2584012ae8608d9765712d3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637670938629884867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eIkNQQX3MNyfuWmfXtH%2FMCo3gt3iUAHP74%2FL7iS0VIA%3D&reserved=0>.
